services:
  - type: web
    name: beat-the-ats
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m nltk.downloader punkt stopwords -q
      python -m spacy download en_core_web_sm --quiet
    startCommand: gunicorn app:app
    plan: free
